/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { stringify } from "query-string";

const initialText = `iPhone\nProtocol Labs Shirt\nFigma Hat (Cyrillic)\nTorn Jeans\nDusty Vans\nHoodie with Pockets\nFigma Fanny Pack\nWedding Band`;

const imgLoadedSet = new Set<string>();

function useDebounce(value: string, delay: number = 300) {
  const [debouncedValue, setDebouncedValue] = useState(value);
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value);
    }, delay);
    return () => {
      clearTimeout(handler);
    };
  }, [value, delay]);
  return debouncedValue;
}

const Home: NextPage = () => {
  const [textArea, setTextArea] = useState<string>(initialText);
  const debouncedTextArea = useDebounce(textArea, 300);
  const [lootImgSrc, setLootImgSrc] = useState<string>("#");
  const [lootImgLoading, setLootImgLoading] = useState<boolean>(false);

  const handleChange = useCallback((e) => {
    setTextArea(e.target.value);
  }, []);

  const generateLootImageUrl = useCallback(() => {
    const lootRows = debouncedTextArea.split("\n").filter((x) => !!x);
    const queryParams = stringify({
      loot: lootRows.join("|"),
    });
    const url = `https://loot-image-generator.vercel.app/api?${queryParams}`;
    if (!imgLoadedSet.has(url)) {
      setLootImgLoading(true);
    }
    setLootImgSrc(url);
  }, [debouncedTextArea]);

  useEffect(() => {
    generateLootImageUrl();
  }, [generateLootImageUrl]);

  const handleImageLoad = useCallback(() => {
    imgLoadedSet.add(lootImgSrc);
    setLootImgLoading(false);
  }, [lootImgSrc]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Show your loot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ marginBottom: 32 }} className={styles.title}>
          {`What's your loot today?`}
        </h1>
        <div style={{ marginBottom: 16 }}>
          <textarea
            placeholder={`iPhone
Macbook Air
Cold brew
Backpack`}
            cols={30}
            rows={20}
            value={textArea}
            onChange={handleChange}
          />
        </div>
        <button onClick={generateLootImageUrl} style={{ marginBottom: 24 }}>
          Get image
        </button>
        {lootImgLoading && <div>Loading image...</div>}
        <div>
          <img
            src={lootImgSrc}
            onLoad={handleImageLoad}
            alt={"Generated loot img"}
            height={538}
            width={538}
          />
        </div>
        <div>
          <a target="_blank" rel="noreferrer" href={lootImgSrc}>
            View loot image
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
